#!/usr/bin/env node
// Regenerate every consumer of cljgo's defining forms from the single source
// of truth, definers.json.
//
// cljgo is homoiconic: a definition has no node type of its own. `(defn f …)`
// is an ordinary list whose head symbol carries the meaning and whose second
// element is the name. So every tool that wants to find a definition needs the
// same list of head symbols — editors to highlight and indent them,
// ctx-optimize to emit them as graph nodes. Four hand-kept copies drift.
//
//   node tools/gen-editors.js           # write
//   node tools/gen-editors.js --check   # verify in sync (CI)

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const BANNER =
  "GENERATED by tools/gen-editors.js from definers.json — do not edit by hand.";

const spec = JSON.parse(fs.readFileSync(path.join(ROOT, "definers.json"), "utf8"));
const all = [...(spec.clojure_core || []), ...(spec.bri || [])];
if (all.length === 0) {
  console.error("definers.json defines no forms");
  process.exit(1);
}

// A namespace-qualified head (`clojure.core/in-ns`) is kept only for
// ctx-optimize, which matches head text exactly. The tree-sitter query matches
// on `!namespace` so it cannot match one, and put-clojure-indent takes a bare
// symbol.
const qualified = (h) => h.includes("/");

// Longest first so alternation prefers `defn-` over `defn`, `defroutes` over
// `defroute`.
const heads = all
  .map((d) => d.head)
  .filter((h) => !qualified(h))
  .sort((a, b) => b.length - a.length || a.localeCompare(b));

const escapeTs = (s) => s.replace(/[-?!*+.]/g, (c) => "\\" + c);

function tsQuery() {
  return (
    `;; ${BANNER}\n;;\n` +
    ";; Every defining form cljgo knows, as @keyword in head position.\n" +
    ";; Layer with `;; extends` in nvim's after/queries/clojure/.\n\n" +
    "(list_lit\n  .\n  (sym_lit\n    !namespace\n    name: (sym_name) @keyword\n" +
    `    (#match? @keyword "^(${heads.map(escapeTs).join("|")})$")))\n`
  );
}

function elisp() {
  const lines = all
    .filter((d) => !qualified(d.head))
    .map((d) => `  (put-clojure-indent '${d.head} '${d.indent})`)
    .join("\n");
  return (
    `;;; definers.el --- ${BANNER}  -*- lexical-binding: t; -*-\n\n` +
    ";;; Commentary:\n;; Indent rules for every cljgo defining form.\n\n;;; Code:\n\n" +
    "(require 'clojure-mode nil t)\n\n" +
    "(defun cljgo--apply-definer-indents ()\n" +
    '  "Apply indentation to cljgo\'s defining forms."\n' +
    lines +
    ")\n\n(provide 'definers)\n;;; definers.el ends here\n"
  );
}

// A TextMate INJECTION grammar: VS Code merges it into the host scope, so the
// hand-maintained cljgo.tmLanguage.json never has to be rewritten.
function tmGrammar() {
  return (
    JSON.stringify(
      {
        _generated: BANNER,
        scopeName: "cljgo.definers.injection",
        injectionSelector: "L:source.cljgo",
        patterns: [
          {
            comment: "every cljgo defining form in head position",
            match: `(?<=\\()(${heads.join("|")})(?=[\\s)])`,
            name: "keyword.control.definer.cljgo",
          },
        ],
      },
      null,
      2
    ) + "\n"
  );
}

// The ctx-optimize pack. decl_rules, not decls: a Clojure declaration has no
// node type, so match the head symbol and read the name from the next element.
// Two rules because `(in-ns 'app.core)` quotes its name.
function pack() {
  const plain = {};
  const quoted = {};
  for (const d of all) (d.quoted_name ? quoted : plain)[d.head] = d.kind;

  const rules = [
    {
      node: "list_lit",
      head_type: "sym_lit",
      name_type: "sym_lit",
      skip_inside: spec.skip_inside,
      head_match: plain,
    },
  ];
  if (Object.keys(quoted).length) {
    rules.push({
      node: "list_lit",
      head_type: "sym_lit",
      name_type: "sym_lit",
      name_unwrap: ["quoting_lit", "syn_quoting_lit"],
      skip_inside: ["dis_expr"],
      head_match: quoted,
    });
  }
  return (
    JSON.stringify(
      { _generated: BANNER, name: "cljgo", exts: spec.exts, decl_rules: rules, names: ["sym_name"] },
      null,
      2
    ) + "\n"
  );
}

const outputs = {
  "queries/generated/definers.scm": tsQuery(),
  "editors/emacs/generated/definers.el": elisp(),
  "editors/vscode/generated/definers.json": tmGrammar(),
  ".ctxoptimize/grammars/cljgo.json": pack(),
};

const check = process.argv.includes("--check");
let stale = 0;
for (const rel of Object.keys(outputs).sort()) {
  const abs = path.join(ROOT, rel);
  if (check) {
    let cur = null;
    try {
      cur = fs.readFileSync(abs, "utf8");
    } catch {}
    if (cur !== outputs[rel]) {
      console.log(`STALE ${rel}`);
      stale++;
    }
    continue;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, outputs[rel]);
  console.log(`wrote ${rel}`);
}
if (check) {
  if (stale) {
    console.error(`\n${stale} file(s) stale — run: node tools/gen-editors.js`);
    process.exit(1);
  }
  console.log("generated files in sync");
}
